spring:
  datasource:
    username: sa
    password: ""
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver

  jpa:
    open-in-view: false
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      use-new-id-generator-mappings: true
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 500
        format_sql: true
        use_sql_comments: true

---
spring:
  config:
    activate:
      on-profile: "test"

hello:
  world: "Hello world"

---
spring:
  config:
    activate:
      on-profile: "local"

---
spring:
  config:
    activate:
      on-profile: "dev"

---
spring:
  config:
    activate:
      on-profile: "prd"